Sprint 4
aromanovnik/middle.messenger.praktikum.yandex pull request #17
Opened 2023-02-12 14:11 UTC by aromanovnik

2023-02-12 15:31 UTC, maks88sgt requested changes
Привет. Отличная работа, у тебя получился классный проект с хорошей архитектурой и чистым кодом. Чтобы закрыть критерии спринта нужно немного доработать проект:
1. Исправить уязвимости в зависимостях, сейчас отчет выдает 
<img width="344" alt="image" src="https://user-images.githubusercontent.com/49103217/218320357-cb3b5e54-8117-4c29-8cf4-cc84fb668dc7.png">
2. Добавить тест сьют для роутера, т.к. по заданию он тоже должен быть покрыт тестами
В целом это все основные замечания. Поправим их и идем дальше.

2023-02-12 15:31 UTC, maks88sgt commented on jest.config.ts
> +  // watchman: true,
Не думаю, что стоит оставлять эти поясняющие комментарии в проекте

2023-02-12 20:33 UTC, aromanovnik commented
-  npm audit  сделал
- тесты по роутингу были 
   1. https://github.com/aromanovnik/middle.messenger.praktikum.yandex/blob/sprint_4/src/core/router.test.ts
   2. https://github.com/aromanovnik/middle.messenger.praktikum.yandex/blob/sprint_4/src/pages/user-details/user-details.page.test.ts

2023-02-12 20:39 UTC, aromanovnik commented on jest.config.ts
> +  // watchman: true,
Удалил, но по опыту сказу, что это удобно.

2023-02-12 20:50 UTC, aromanovnik commented
Добавил еще тесты для роутинга.

2023-02-13 03:37 UTC, maks88sgt commented
Отлично! Работу принял, успехов на курсе!

2023-02-13 10:56 UTC, merged